import turtle

def hexagon(side):
    turtle.forward(side)
    turtle.setheading(60)

    turtle.forward(side)
    turtle.setheading(120)

    turtle.forward(side)
    turtle.setheading(180)

    turtle.forward(side)
    turtle.setheading(240)

    turtle.forward(side)
    turtle.setheading(300)

    turtle.forward(side)
turtle.showturtle()
side = 100
hexagon(side)
turtle.setheading(240)
turtle.forward(side)
turtle.setheading(180)
turtle.forward(side)
turtle.setheading(0)
hexagon(side)
turtle.setheading(0)
turtle.forward(side)
turtle.setheading(300)
turtle.forward(side)
turtle.setheading(0)
hexagon(side)
turtle.setheading(0)
turtle.forward(side)
turtle.setheading(60)
turtle.forward(side)
turtle.setheading(0)
hexagon(side)
turtle.setheading(120)
turtle.forward(side)
turtle.setheading(60)
turtle.forward(side)
turtle.setheading(0)
hexagon(side)
turtle.setheading(120)
turtle.forward(side)
turtle.setheading(180)
turtle.forward(side)
turtle.setheading(0)
hexagon(side)
turtle.setheading(240)
turtle.forward(side)
turtle.setheading(180)
turtle.forward(side)
turtle.setheading(0)
hexagon(side)